# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10fbd59017f62ad471caa7f3441d823d8619d65b098503b17253020e8157efb05af66ee302ea008b1f740955faeeb1964848157ab96bbef174fd6fa497548db3

test:
  secret_key_base: 5ff22504ceb4822e131e49a5380b4daaafa1de29203dd609d8047001697467b0aade89350e2fbf3dee4aeafa6041e25839b2c765c630dda5202cbc3e1bdbcb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
